motion_vae:
  target: mld.models.architectures.mld_vae.MldVaeV2
  params:
    nfeats: ${DATASET.NFEATS}
    latent_dim: ${model.latent_dim}
    hidden_dim: 512
    down_t: 2
    stride_t: 2
    n_depth: 3
    dilation_growth_rate: 3
    activation: 'relu'
    dropout: 0.1
    norm: null
    norm_groups: 32
    norm_eps: 1e-5
    clip_range: null
