motion_vae:
  target: mld.models.architectures.mld_vae.MldVae
  params:
    arch: 'encoder_decoder'
    ff_size: 1024
    num_layers: 9
    num_heads: 4
    dropout: 0.1
    normalize_before: false
    activation: 'gelu'
    position_embedding: 'learned'
    latent_dim: ${model.latent_dim}
    nfeats: ${DATASET.NFEATS}
