motion_vae:
  target: mld.models.architectures.mld_vae.MldVaeV2
  params:
    nfeats: ${DATASET.NFEATS}
    latent_dim: ${model.latent_dim}
    down_t: 4
    stride_t: 2
    n_depth: 3
    dilation_growth_rate: 3
    activation: 'relu'
    dropout: 0.2
    norm: None
    norm_groups: 32
    norm_eps: 1e-6
    clip_range: [-30.0, 20.0]
