noise_optimizer:
  target: mld.models.architectures.dno.DNO
  params:
    max_train_steps: 100
    learning_rate: 0.2
    lr_scheduler: 'cosine'
    lr_warmup_steps: 50
    clip_grad: true
    loss_diff_penalty: 0.002
    loss_correlate_penalty: 1000
    visualize: true
    visualize_samples: 4
    visualize_ske_steps: [1, 100]
    output_dir: ${output_dir}
