noise_optimizer:
  target: mld.models.architectures.dno.DNO
  params:
    max_train_steps: 800
    learning_rate: 0.02
    lr_scheduler: 'cosine'
    lr_warmup_steps: 50
    loss_diff_penalty: 0
    loss_correlate_penalty: 0
    visualize: true
    visualize_samples: 4
    output_dir: ${output_dir}
