noise_optimizer:
  target: mld.models.architectures.dno.DNO
  params:
    max_train_steps: 800
    learning_rate: 0.02
    lr_scheduler: 'cosine'
    lr_warmup_steps: 50
    loss_diff_penalty: 0.002
    loss_correlate_penalty: 1000
