noise_optimizer:
  target: mld.models.architectures.dno.DNO
  params:
    optimize: false
    max_train_steps: 400
    learning_rate: 0.5
    lr_scheduler: 'cosine'
    lr_warmup_steps: 100
    clip_grad: true
    loss_hint_type: 'l2'
    loss_diff_penalty: 0.000
    loss_correlate_penalty: 1000
    visualize_samples: 0
    visualize_ske_steps: [1, 100, 200, 300, 400]
    output_dir: ${output_dir}
