noise_optimizer:
  target: mld.models.architectures.dno.DNO
  params:
    max_train_steps: 400
    learning_rate: 0.5
    lr_scheduler: 'cosine'
    lr_warmup_steps: 100
    clip_grad: true
    loss_diff_penalty: 0
    loss_correlate_penalty: 0
    visualize: true
    visualize_samples: 'inf'
    visualize_ske_steps: []
    output_dir: ${output_dir}
