noise_optimizer:
  target: mld.models.architectures.dno.DNO
  params:
    max_train_steps: 800
    learning_rate: 0.4
    lr_scheduler: 'cosine'
    lr_warmup_steps: 50
    clip_grad: true
    loss_diff_penalty: 0.002
    loss_correlate_penalty: 1000
    visualize: true
    visualize_samples: 1
    visualize_ske_steps: [1, 100, 200, 300, 400, 500, 600, 700, 800]
    output_dir: ${output_dir}
