scheduler:
  target: diffusers.DDIMScheduler
  num_inference_steps: 50
  eta: 0.0
  params:
    num_train_timesteps: 1000
    beta_start: 0.00085
    beta_end: 0.012
    beta_schedule: 'scaled_linear'
    prediction_type: 'epsilon'
    clip_sample: false
    # below are for ddim
    set_alpha_to_one: false
    steps_offset: 1
