text_encoder:
  target: mld.models.architectures.mld_clip.MldTextEncoder
  params:
    last_hidden_state: true # if true, the last hidden state is used as the text embedding
    modelpath: ${model.clip_path}
