FOLDER: './experiments_t2m'
TEST_FOLDER: './experiments_t2m_test'

NAME: 'mld_humanml'

TRAIN:
  DATASETS: ['humanml3d']
  BATCH_SIZE: 1
  NUM_WORKERS: 8
  PERSISTENT_WORKERS: true
  SEED_VALUE: 1234

EVAL:
  DATASETS: ['humanml3d']
  BATCH_SIZE: 32
  SPLIT: test
  NUM_WORKERS: 12

TEST:
  DATASETS: ['humanml3d']
  SPLIT: test
  BATCH_SIZE: 1
  NUM_WORKERS: 12

  CHECKPOINTS: 'experiments_t2m/mld_humanml/mld_humanml.ckpt'

  # Testing Args
  REPLICATION_TIMES: 20
  MM_NUM_SAMPLES: 100
  MM_NUM_REPEATS: 30
  MM_NUM_TIMES: 10
  DIVERSITY_TIMES: 300

DATASET:
  SMPL_PATH: './deps/smpl'
  WORD_VERTILIZER_PATH: './deps/glove/'
  HUMANML3D:
    PICK_ONE_TEXT: true
    FRAME_RATE: 20.0
    UNIT_LEN: 4
    ROOT: './datasets/humanml3d'
    SPLIT_ROOT: './datasets/humanml3d'
  SAMPLER:
    MAX_LEN: 196
    MIN_LEN: 40
    MAX_TEXT_LEN: 20

METRIC:
  DIST_SYNC_ON_STEP: True
  TYPE: ['TM2TMetrics']

model:
  target: 'modules_mld'
  latent_dim: [1, 256]
  guidance_scale: 7.5

  t2m_textencoder:
    dim_word: 300
    dim_pos_ohot: 15
    dim_text_hidden: 512
    dim_coemb_hidden: 512

  t2m_motionencoder:
    dim_move_hidden: 512
    dim_move_latent: 512
    dim_motion_hidden: 1024
    dim_motion_latent: 512

  bert_path: './deps/distilbert-base-uncased'
  clip_path: './deps/clip-vit-large-patch14'
  t5_path: './deps/sentence-t5-large'
  t2m_path: './deps/t2m/'
