FOLDER: './experiments_recons'
TEST_FOLDER: './experiments_recons_test'

NAME: 'vae_humanml'

SEED_VALUE: 1234

TRAIN:
  BATCH_SIZE: 128
  SPLIT: 'train'
  NUM_WORKERS: 8
  PERSISTENT_WORKERS: true
  PRETRAINED: ''

  validation_steps: -1
  validation_epochs: 100
  checkpointing_steps: -1
  checkpointing_epochs: 100
  max_train_steps: -1
  max_train_epochs: 6000
  learning_rate: 2e-4
  lr_scheduler: "cosine"
  lr_warmup_steps: 1000
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 0.0
  adam_epsilon: 1e-08
  max_grad_norm: 1.0

VAL:
  BATCH_SIZE: 32
  SPLIT: 'test'
  NUM_WORKERS: 12
  PERSISTENT_WORKERS: true

TEST:
  BATCH_SIZE: 32
  SPLIT: 'test'
  NUM_WORKERS: 12
  PERSISTENT_WORKERS: true

  CHECKPOINTS: 'experiments_recons/vae_humanml/vae_humanml.ckpt'

  # Testing Args
  REPLICATION_TIMES: 20
  DIVERSITY_TIMES: 300
  DO_MM_TEST: false

DATASET:
  NAME: 'humanml3d'
  SMPL_PATH: './deps/smpl'
  WORD_VERTILIZER_PATH: './deps/glove/'
  HUMANML3D:
    FRAME_RATE: 20.0
    UNIT_LEN: 4
    ROOT: './datasets/humanml3d'
    CONTROL_ARGS:
      CONTROL: false
      TEMPORAL: false
      TRAIN_JOINTS: [0]
      TEST_JOINTS: [0]
      TRAIN_DENSITY: 'random'
      TEST_DESITY: 100
      MEAN_STD_PATH: './datasets/humanml_spatial_norm'
  SAMPLER:
    MAX_LEN: 200
    MIN_LEN: 40
    MAX_TEXT_LEN: 20
  PADDING_TO_MAX: true
  WINDOW_SIZE: 64

METRIC:
  DIST_SYNC_ON_STEP: true
  TYPE: ['TM2TMetrics', "PosMetrics"]

model:
  target: ['motion_vae']
  latent_dim: [16, 32]

  # VAE Args
  rec_feats_ratio: 1.0
  rec_joints_ratio: 1.0
  rec_velocity_ratio: 0.0
  kl_ratio: 1e-4

  rec_feats_loss: 'l1_smooth'
  rec_joints_loss: 'l1_smooth'
  rec_velocity_loss: 'l1_smooth'
  mask_loss: true

  t2m_textencoder:
    dim_word: 300
    dim_pos_ohot: 15
    dim_text_hidden: 512
    dim_coemb_hidden: 512

  t2m_motionencoder:
    dim_move_hidden: 512
    dim_move_latent: 512
    dim_motion_hidden: 1024
    dim_motion_latent: 512

  t2m_path: './deps/t2m/'
