traj_encoder:
  target: mld.models.architectures.mld_traj_encoder.MldTrajEncoder
  params:
    ff_size: 1024
    num_layers: 9
    num_heads: 4
    dropout: 0.1
    normalize_before: false
    activation: 'gelu'
    position_embedding: 'learned'
    latent_dim: ${model.latent_dim}
    nfeats: ${DATASET.NJOINTS}
